# .travis.yml
# sudo: false
language: cpp

notifications:
  email: false
  slack: axiommarkets:uQPCDh2hZ26jzOx3TyWEnpDe

before_install:
- pip install --user cpp-coveralls
- pip install --user pyyaml 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository ppa:apokluda/boost1.53 --yes
- sudo apt-get update -qq

install:

- sudo apt-get install -qq g++-4.8
#- sudo apt-get install -qq ggcov-4.8
- export CXX="g++-4.8"
- export GCOV="gcov-4.8"
- sudo apt-get install libboost1.53-all-dev
#- sudo apt-get install libboost-system-dev
#- sudo apt-get install libboost-thread-dev
#- sudo apt-get install libboost-test-dev

before_script:
- echo ${PWD}
- /usr/bin/${CXX} --version
- /usr/bin/${GCOV} --version
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/${PWD}/lib
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib

script: ./test_travis.sh

after_failure:

  
after_success:
   - ls
  - coveralls --exclude boost --verbose --exclude tests --gcov /usr/bin/${GCOV} --gcov-options '../*.cpp -o'
