# .travis.yml
# sudo: false
language: cpp

notifications:
  email: false
  slack: axiommarkets:uQPCDh2hZ26jzOx3TyWEnpDe

env:
  global:
    - export REPO="AxiomMarketsLLC/ax_fast_log"
    - export CLI_HOME=`pwd`/$REPO

compiler:
  - g++-4.8

before_install:
 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sud oapt-get install -qq g++-4.8
- export CXX="g++-4.8"

script: "bash -c ./test_travis.sh"

after_failure:

  
after_success:
  - coveralls --exclude boost --exclude tests --gcov-options 'src/*.cpp -o'
