# .travis.yml
# sudo: false
language: cpp

notifications:
  email: false
  slack: axiommarkets:uQPCDh2hZ26jzOx3TyWEnpDe

env:
  global:
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/build/travis/AxiomMarketsLLC/ax_fast_log/lib/
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/build/travis/AxiomMarketsLLC/ax_fast_log/libs/

before_install:
 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

script: ./test_travis.sh

after_failure:

  
after_success:
  - coveralls --exclude boost --exclude tests --gcov-options 'src/*.cpp -o'
