# .travis.yml
# sudo: false
language: cpp

notifications:
  email: false
  slack: axiommarkets:uQPCDh2hZ26jzOx3TyWEnpDe

compiler:
  - g++

before_install:
 
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install pwd
- sudo apt-get install -qq g++-4.8

script:
  - ./test.sh --log_level=test_suite

after_failure:

  
after_success:
  - coveralls --exclude boost --exclude tests --gcov-options 'src/*.cpp -o'
